"""fix frozen literal timestamp defaults to use now function

Revision ID: 272522799dab
Revises: 441fedb081f0
Create Date: 2026-08-05 18:01:53.642289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '272522799dab'
down_revision: Union[str, None] = '441fedb081f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_grants', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('active_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('active_sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('backups', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('boundary_shapefiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('cms_blocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('dataset_requests', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('download_logs', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('failed_logins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('media_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('quality_issues', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('subset_extractions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploads', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('subset_extractions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('quality_issues', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('media_files', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('failed_logins', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('download_logs', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('dataset_requests', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('cms_blocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('boundary_shapefiles', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('blog_posts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('blog_posts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('backups', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('active_sessions', 'last_active_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('active_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('access_grants', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-05 10:59:33.000133+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
