"""add format column and indexes to subset_extractions

Revision ID: 390d9b062aca
Revises: eeb3f06d4862
Create Date: 2026-08-05 18:28:06.456072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '390d9b062aca'
down_revision: Union[str, None] = 'eeb3f06d4862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subset_extractions', sa.Column('format', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_subset_extractions_grant_id'), 'subset_extractions', ['grant_id'], unique=False)
    op.create_index(op.f('ix_subset_extractions_status'), 'subset_extractions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subset_extractions_status'), table_name='subset_extractions')
    op.drop_index(op.f('ix_subset_extractions_grant_id'), table_name='subset_extractions')
    op.drop_column('subset_extractions', 'format')
    # ### end Alembic commands ###
