"""initial schema

Revision ID: 441fedb081f0
Revises: 
Create Date: 2026-08-05 15:27:59.094760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '441fedb081f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_team_members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_key', sa.String(length=1024), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backups',
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_blocks',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_cms_blocks_page'), 'cms_blocks', ['page'], unique=False)
    op.create_table('dataset_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_tag', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('failed_logins',
    sa.Column('email_attempted', sa.String(length=320), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_logins_created_at'), 'failed_logins', ['created_at'], unique=False)
    op.create_index(op.f('ix_failed_logins_email_attempted'), 'failed_logins', ['email_attempted'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('data_access_email', sa.String(length=320), nullable=True),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=False),
    sa.Column('session_lifetime_min', sa.Integer(), nullable=False),
    sa.Column('notify_new_request', sa.Boolean(), nullable=False),
    sa.Column('notify_new_user', sa.Boolean(), nullable=False),
    sa.Column('notify_expiring_dataset', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('research_area', sa.String(length=255), nullable=True),
    sa.Column('datasets_granted', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('active_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_jti', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_jti')
    )
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.create_table('admin_team_members',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action_type'), 'audit_log', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tag_key', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('featured_image_key', sa.String(length=1024), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boundary_shapefiles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('parameters', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('resolution', sa.String(length=100), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('processing_levels', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('formats', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spatial_extent', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('temporal_start', sa.Date(), nullable=True),
    sa.Column('temporal_end', sa.Date(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dataset_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # NOTE: the GIST spatial index on spatial_extent is created automatically by
    # GeoAlchemy2's DDL event listener (spatial_index=True on the column) — an
    # explicit op.create_index here would collide with it, so it's intentionally
    # omitted (same for dataset_files.spatial_extent and dataset_records.geom below).
    op.create_index(op.f('ix_datasets_status'), 'datasets', ['status'], unique=False)
    op.create_table('media_files',
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('date_range', sa.String(length=100), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('output_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_files',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_backend', sa.String(length=20), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('spatial_extent', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('temporal_start', sa.Date(), nullable=True),
    sa.Column('temporal_end', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.Date(), nullable=True),
    sa.Column('file_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # (spatial GIST index auto-created by GeoAlchemy2 — see note above)
    op.create_table('dataset_records',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Date(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=True),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quality_flag', sa.String(length=20), nullable=False),
    sa.Column('processing_level', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # (spatial GIST index auto-created by GeoAlchemy2 — see note above)
    op.create_index(op.f('ix_dataset_records_dataset_id'), 'dataset_records', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_records_parameter'), 'dataset_records', ['parameter'], unique=False)
    op.create_index(op.f('ix_dataset_records_time'), 'dataset_records', ['time'], unique=False)
    op.create_table('quality_issues',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('search_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supporting_document_file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supporting_document_file_id'], ['dataset_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_requests_status'), 'dataset_requests', ['status'], unique=False)
    op.create_index(op.f('ix_dataset_requests_user_id'), 'dataset_requests', ['user_id'], unique=False)
    op.create_table('uploads',
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('dataset_file_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_file_id'], ['dataset_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_grants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['dataset_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_grants_status'), 'access_grants', ['status'], unique=False)
    op.create_index(op.f('ix_access_grants_user_id'), 'access_grants', ['user_id'], unique=False)
    op.create_table('subset_extractions',
    sa.Column('grant_id', sa.UUID(), nullable=False),
    sa.Column('requested_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output_storage_backend', sa.String(length=20), nullable=True),
    sa.Column('output_bucket', sa.String(length=255), nullable=True),
    sa.Column('output_file_key', sa.String(length=1024), nullable=True),
    sa.Column('output_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['access_grants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_logs',
    sa.Column('grant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subset_extraction_id', sa.UUID(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['access_grants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subset_extraction_id'], ['subset_extractions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download_logs')
    op.drop_table('subset_extractions')
    op.drop_index(op.f('ix_access_grants_user_id'), table_name='access_grants')
    op.drop_index(op.f('ix_access_grants_status'), table_name='access_grants')
    op.drop_table('access_grants')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_dataset_requests_user_id'), table_name='dataset_requests')
    op.drop_index(op.f('ix_dataset_requests_status'), table_name='dataset_requests')
    op.drop_table('dataset_requests')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_dataset_records_time'), table_name='dataset_records')
    op.drop_index(op.f('ix_dataset_records_parameter'), table_name='dataset_records')
    op.drop_index(op.f('ix_dataset_records_dataset_id'), table_name='dataset_records')
    op.drop_table('dataset_records')
    op.drop_table('dataset_files')
    op.drop_table('user_roles')
    op.drop_table('support_tickets')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_datasets_status'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('boundary_shapefiles')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action_type'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admin_team_members')
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stations')
    op.drop_table('site_settings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_failed_logins_email_attempted'), table_name='failed_logins')
    op.drop_index(op.f('ix_failed_logins_created_at'), table_name='failed_logins')
    op.drop_table('failed_logins')
    op.drop_table('dataset_categories')
    op.drop_index(op.f('ix_cms_blocks_page'), table_name='cms_blocks')
    op.drop_table('cms_blocks')
    op.drop_table('backups')
    op.drop_table('about_team_members')
    # ### end Alembic commands ###
