"""add storage capacity and daily stats snapshot

Revision ID: 47574d3ca56a
Revises: 59bea90da019
Create Date: 2026-08-06 15:10:52.638978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47574d3ca56a'
down_revision: Union[str, None] = '59bea90da019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unrelated server_default drift on the pre-existing viz_* columns
    # (a Python-default-vs-DB-server_default artifact autogenerate detects
    # every time, same as dac3920b66e4) is intentionally omitted here to
    # leave those columns untouched.
    op.create_table('daily_stats_snapshots',
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('total_datasets', sa.Integer(), nullable=False),
    sa.Column('pending_requests', sa.Integer(), nullable=False),
    sa.Column('total_downloads', sa.Integer(), nullable=False),
    sa.Column('active_grants', sa.Integer(), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_snapshots_snapshot_date'), 'daily_stats_snapshots', ['snapshot_date'], unique=True)
    op.add_column('site_settings', sa.Column('storage_capacity_bytes', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'storage_capacity_bytes')
    op.drop_index(op.f('ix_daily_stats_snapshots_snapshot_date'), table_name='daily_stats_snapshots')
    op.drop_table('daily_stats_snapshots')
    # ### end Alembic commands ###
