"""add phase9 content columns

Revision ID: 7b47c9726835
Revises: a3c47b895dae
Create Date: 2026-08-06 19:46:03.849731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b47c9726835'
down_revision: Union[str, None] = 'a3c47b895dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unrelated server_default drift on the pre-existing viz_* columns (a
    # Python-default-vs-DB-server_default artifact autogenerate detects
    # every time this project runs it, same as every prior migration) is
    # intentionally omitted here to leave those columns untouched.
    op.add_column('about_team_members', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'about_team_members', 'media_files', ['photo_id'], ['id'], ondelete='SET NULL')
    op.drop_column('about_team_members', 'photo_key')

    op.add_column('blog_posts', sa.Column('featured_image_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'media_files', ['featured_image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('blog_posts', 'featured_image_key')

    op.add_column('media_files', sa.Column('alt_text', sa.String(length=255), nullable=True))
    op.add_column('media_files', sa.Column('title', sa.String(length=255), nullable=True))

    # cms_blocks: `key` is the current primary key. Swap to a real UUID
    # `id` primary key, keeping `key` as a separate unique-indexed column
    # (immutable after create at the application layer) — Custom Blocks
    # need identity independent of a human-editable key. server_default
    # gen_random_uuid() backfills any existing rows atomically in the same
    # statement (table is empty in every environment observed so far, but
    # this is correct even if it weren't).
    op.add_column(
        'cms_blocks',
        sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    )
    op.add_column('cms_blocks', sa.Column('section', sa.String(length=100), nullable=True))
    op.add_column('cms_blocks', sa.Column('display_order', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('cms_blocks', sa.Column('is_system_block', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('cms_blocks', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.drop_constraint('cms_blocks_pkey', 'cms_blocks', type_='primary')
    op.create_primary_key('cms_blocks_pkey', 'cms_blocks', ['id'])
    op.create_index(op.f('ix_cms_blocks_key'), 'cms_blocks', ['key'], unique=True)
    op.alter_column('cms_blocks', 'id', server_default=None)
    op.alter_column('cms_blocks', 'display_order', server_default=None)
    op.alter_column('cms_blocks', 'is_system_block', server_default=None)
    op.alter_column('cms_blocks', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_blocks_key'), table_name='cms_blocks')
    op.drop_constraint('cms_blocks_pkey', 'cms_blocks', type_='primary')
    op.create_primary_key('cms_blocks_pkey', 'cms_blocks', ['key'])
    op.drop_column('cms_blocks', 'is_active')
    op.drop_column('cms_blocks', 'is_system_block')
    op.drop_column('cms_blocks', 'display_order')
    op.drop_column('cms_blocks', 'section')
    op.drop_column('cms_blocks', 'id')

    op.drop_column('media_files', 'title')
    op.drop_column('media_files', 'alt_text')

    op.add_column('blog_posts', sa.Column('featured_image_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'featured_image_id')

    op.add_column('about_team_members', sa.Column('photo_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'about_team_members', type_='foreignkey')
    op.drop_column('about_team_members', 'photo_id')
    # ### end Alembic commands ###
