"""add visualization jobs and site settings export toggles

Revision ID: cd79ed2d5105
Revises: 4c47c62a00e4
Create Date: 2026-08-06 10:14:30.953116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = 'cd79ed2d5105'
down_revision: Union[str, None] = '4c47c62a00e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualization_jobs',
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visualization_jobs_job_type'), 'visualization_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_visualization_jobs_status'), 'visualization_jobs', ['status'], unique=False)
    op.add_column('site_settings', sa.Column('viz_export_temporal_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('site_settings', sa.Column('viz_export_spatial_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('site_settings', sa.Column('viz_export_comparison_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('site_settings', sa.Column('viz_export_statistics_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'viz_export_statistics_enabled')
    op.drop_column('site_settings', 'viz_export_comparison_enabled')
    op.drop_column('site_settings', 'viz_export_spatial_enabled')
    op.drop_column('site_settings', 'viz_export_temporal_enabled')
    op.drop_index(op.f('ix_visualization_jobs_status'), table_name='visualization_jobs')
    op.drop_index(op.f('ix_visualization_jobs_job_type'), table_name='visualization_jobs')
    op.drop_table('visualization_jobs')
    # ### end Alembic commands ###
