"""add viz compute limit settings

Revision ID: dac3920b66e4
Revises: cd79ed2d5105
Create Date: 2026-08-06 12:58:50.217729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'dac3920b66e4'
down_revision: Union[str, None] = 'cd79ed2d5105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated) so this doesn't
    # violate NOT NULL against the existing site_settings row — matches
    # the same fix applied to Phase 7's viz_export_*_enabled migration.
    op.add_column('site_settings', sa.Column('viz_max_grid_resolution', sa.Integer(), nullable=False, server_default=sa.text('100')))
    op.add_column('site_settings', sa.Column('viz_max_aoi_km2', sa.Float(), nullable=False, server_default=sa.text('500.0')))
    op.add_column('site_settings', sa.Column('viz_max_date_range_days_spatial', sa.Integer(), nullable=True, server_default=sa.text('3650')))
    op.add_column('site_settings', sa.Column('viz_max_date_range_days_timeseries', sa.Integer(), nullable=True))
    op.add_column('site_settings', sa.Column('viz_max_date_range_days_comparison', sa.Integer(), nullable=True))
    op.add_column('site_settings', sa.Column('viz_max_date_range_days_statistics', sa.Integer(), nullable=True))
    # Note: autogenerate also proposed dropping server_default from the
    # existing viz_export_*_enabled columns (a Python-default-vs-DB-
    # server_default drift Alembic detected, unrelated to this change) —
    # intentionally omitted here to leave those columns untouched.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'viz_max_date_range_days_statistics')
    op.drop_column('site_settings', 'viz_max_date_range_days_comparison')
    op.drop_column('site_settings', 'viz_max_date_range_days_timeseries')
    op.drop_column('site_settings', 'viz_max_date_range_days_spatial')
    op.drop_column('site_settings', 'viz_max_aoi_km2')
    op.drop_column('site_settings', 'viz_max_grid_resolution')
    # ### end Alembic commands ###
